### ISSUE TITLE
Resize errors in some symbols

### ISSUE THREAD

**Issue by ShaneNZ** [jydesign/Sketch-Hunt_Arrows-and-Lines-Pack#1]
Some of the line ends are set to stretch when the should be pin to corner. Symbols affected:
- Line 06
- Arrow 25
- Arrow 32
  (would have fixed and submitted a PR, but wasn't sure if you wanted to manage merges that way given you might still be working on it - this seemed simpler).

**Comment by jydesign** [comment]
Thanks @ShaneNZ, this kind of helpful feedback is exactly why I moved this version to Github. I'll aim to fix these very soon.

**Comment by jydesign** [comment]
Fixed Line 06 and Arrow 25. Arrow 32 requires new artwork, so I've saved this as its own issue to tackle later.
